[project]
name = "ledger-utils"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
license = { text = "MIT" }
authors = [
  { name = "TATEISHI Tadatoshi", email = "ishio39@gmail.com" }
]

dependencies = [
    "typer>=0.26.7",
]

[dependency-groups]
dev = [
    "mypy>=2.1.0",
    "pytest>=9.0.3",
    "ruff>=0.15.16",
]

[build-system]
requires = ["setuptools>=80","wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
exclude = ["tests"]

[project.scripts]
ledger_utils = "ledger_utils.cli:app"
lu = "ledger_utils.cli:app"
